---
title: "Yeast PHO motif analysis"
author: "Bin He"
date: "11/12/2018"
output: html_document
---

## prepare environment

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install_dependencies}
source("http://bioconductor.org/biocLite.R")
biocLite(c("Biobase", "GEOquery", "limma"))
```

```{r load_libraries_and_data}
library(Biobase)
library(GEOquery)

# load series and platform data from GEO

gset <- getGEO("GSE23580", GSEMatrix =TRUE, getGPL=FALSE)
if (length(gset) > 1) idx <- grep("GPL10786", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# group names for all samples in a series
gsms <- "XXXX0XXXXXXXXXXXXXXX0XXXXXXXXXXXXXXX0XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
sml <- c()
for (i in 1:nchar(gsms)) { sml[i] <- substr(gsms,i,i) }
sml <- paste("G", sml, sep="")  #set group names

# eliminate samples marked as "X"
sel <- which(sml != "X")
sml <- sml[sel]
gset <- gset[ ,sel]

# order samples by group
ex <- exprs(gset)[ , order(sml)]
sml <- sml[order(sml)]
fl <- as.factor(sml)
labels <- c("wt-pho-no-Pi")

# set parameters and draw the plot
palette(c("#dfeaf4", "#AABBCC"))
dev.new(width=4+dim(gset)[[2]]/5, height=6)
par(mar=c(2+round(max(nchar(sampleNames(gset)))/2),4,2,1))
title <- paste ("GSE23580", '/', annotation(gset), " selected samples", sep ='')
boxplot(ex, boxwex=0.6, notch=T, main=title, outline=FALSE, las=2, col=fl)
legend("topleft", labels, fill=palette(), bty="n")
```